version: '3.8'

services:
  stock-dashboard:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - ./stock_data.db:/app/stock_data.db
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    container_name: stock-dashboard

  # Nginx 프록시 (선택사항)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - stock-dashboard
    restart: unless-stopped
    container_name: stock-nginx 